version: 2.1

executors:
  sphinx:
    description: A docker image with spinx-docs and all extensions necessary for fortran and publishing to github pages.
    docker:
      - image: niemacka/sphinx
jobs:
  publish:
    executor: sphinx
    description: Publish sphinx html and pdf documents to gh-pages.
    steps:
      - checkout
      - run:
          command: |
            git config --global user.email "andrewn@ucar.edu"
            git config --global user.name "aNiemack"
            git describe --tags --abbrev=0 > version
            git checkout master
            VERSION=`head -1 version`
            make html
            make latexpdf
            cd _build
            mv latex/ /root/project/
            cd /root/project
            mv latex/ "$VERSION-pdf"
            cd _build
            mv html/ /root/project/
            cd /root/project
            mv html/ "$VERSION-html"
            git add --all
            git commit -m "new docs"
            git checkout gh-pages
            git checkout master "$VERSION-pdf"
            git checkout master "$VERSION-html"
            mv "$VERSION-pdf" _pdfs/
            mv "$VERSION-html" _documents/
            cd _documents/"$VERSION-html"
            echo --- | cat - index.html > temp && mv temp index.html
            echo --- | cat - index.html > temp && mv temp index.html
            mv index.html $VERSION.html
            cd /root/project            
            git add --all
            git commit -m "new version"
            git push -u origin gh-pages 
