version: 2.1

executors:
  sphinx:
    description: A docker image with sphinx-docs and all extensions necessary for fortran and publishing to github pages.
    docker:
      - image: niemacka/sphinx
jobs:
  publish:
    executor: sphinx
    description: Publish sphinx html and pdf documents to gh-pages.
    parameters:
      html:
        description: Location for sphinx html build in gh-pages.
        type: string
        default: "_documents"
      pdf:
        description: Location for sphinx pdf build in gh-pages.
        type: string
        default: "_pdfs"
    steps:
      - checkout
      - run:
          command: |
            git config --global user.email "andrewn@ucar.edu"
            git config --global user.name "aNiemack"
            git describe --tags --abbrev=0 > version
            git checkout master
            VERSION=`head -1 version`
            LOC=$(find /root/project -name conf.py)
            LOC2=${LOC::-7}
            cd $LOC2
            make html
            make latexpdf
            cd _build
            mv latex/ /root/project/
            cd /root/project
            mv latex/ "$VERSION-pdf"
            cd _build
            mv html/ /root/project/
            cd /root/project
            mv html/ "$VERSION-html"
            git add --all
            git commit -m "new docs"
            git checkout gh-pages
            git checkout master "$VERSION-pdf"
            git checkout master "$VERSION-html"
            mkdir -p << parameters.html >>
            mkdir -p << parameters.pdf >>
            mv "$VERSION-pdf" << parameters.pdf >>
            mv "$VERSION-html" << parameters.html >>
            cd << parameters.html >>/"$VERSION-html"
            echo --- | cat - index.html > temp && mv temp index.html
            echo --- | cat - index.html > temp && mv temp index.html
            mv index.html $VERSION.html
            cd /root/project         
            git add --all
            git commit -m "new version"
            git push -u origin gh-pages 
